# NumPy Basics for Mathematical Computing

In [1]:
import numpy as np


## Creating NumPy Arrays

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])  # 1D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D Array
print(f"1D Array: {arr1}")
print(f"2D Array: \n{arr2}")

1D Array: [1 2 3 4 5]
2D Array: 
[[1 2 3]
 [4 5 6]]


## Array Properties

In [3]:
print(f"Shape: {arr2.shape}, Size: {arr2.size}, Data Type: {arr2.dtype}")

Shape: (2, 3), Size: 6, Data Type: int64


## Basic Mathematical Operations

In [4]:
arr_sum = arr1 + 2  # Add scalar
arr_product = arr1 * 3  # Multiply by scalar
arr_sqrt = np.sqrt(arr1)  # Square root

print(f"Array Sum: {arr_sum}")
print(f"Array Product: {arr_product}")
print(f"Square Root: {arr_sqrt}")

Array Sum: [3 4 5 6 7]
Array Product: [ 3  6  9 12 15]
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]


## Matrix Operations

In [5]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_sum = matrix1 + matrix2
matrix_product = np.dot(matrix1, matrix2)  # Matrix multiplication
matrix_transpose = matrix1.T

print(f"Matrix Sum:\n{matrix_sum}")
print(f"Matrix Product:\n{matrix_product}")
print(f"Matrix Transpose:\n{matrix_transpose}")

Matrix Sum:
[[ 6  8]
 [10 12]]
Matrix Product:
[[19 22]
 [43 50]]
Matrix Transpose:
[[1 3]
 [2 4]]


## Generating Special Arrays

In [6]:
zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((2, 2))
random_arr = np.random.rand(3, 3)

print(f"Zeros Array:\n{zeros_arr}")
print(f"Ones Array:\n{ones_arr}")
print(f"Random Array:\n{random_arr}")


Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
[[1. 1.]
 [1. 1.]]
Random Array:
[[0.81258578 0.12574909 0.27789946]
 [0.09683016 0.13222386 0.7623706 ]
 [0.11091833 0.69086525 0.58708684]]
