# Linear Algebra with NumPy


In [1]:
import numpy as np

## Creating Matrices

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]


## Matrix Addition and Subtraction

In [3]:
print("A + B:\n", A + B)
print("A - B:\n", A - B)


A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]


## Scalar Multiplication


In [4]:
print("2 * A:\n", 2 * A)

2 * A:
 [[2 4]
 [6 8]]


## Matrix Multiplication


In [5]:
print("A dot B:\n", np.dot(A, B))


A dot B:
 [[19 22]
 [43 50]]


## Element-wise Multiplication


In [6]:
print("A * B (element-wise):\n", A * B)


A * B (element-wise):
 [[ 5 12]
 [21 32]]


## Transpose


In [7]:
print("Transpose of A:\n", A.T)


Transpose of A:
 [[1 3]
 [2 4]]


## Determinant

In [8]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


## Inverse

In [9]:
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
else:
    print("Matrix A is singular and cannot be inverted.")

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Eigenvalues and Eigenvectors

In [10]:
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## Solving Linear Systems


$Ax = b$

In [11]:
b = np.array([5, 11])
x = np.linalg.solve(A, b)
print("Solution of Ax = b:", x)


Solution of Ax = b: [1. 2.]
